# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-10 05:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField()),
                ('name', models.CharField(max_length=32)),
                ('direction', models.CharField(blank=True, choices=[(None, ''), ('N', 'North'), ('S', 'South'), ('E', 'East'), ('W', 'West')], max_length=1, null=True)),
                ('suffix', models.CharField(blank=True, choices=[(None, ''), ('AV', 'Avenue'), ('BV', 'Boulevard'), ('CR', 'Circle'), ('CT', 'Court'), ('DR', 'Drive'), ('E', 'East'), ('EX', 'Expressway'), ('HY', 'Highway'), ('LN', 'Lane'), ('N', 'North'), ('PK', 'Park'), ('PL', 'Place'), ('RD', 'Road'), ('S', 'South'), ('ST', 'Street'), ('TE', 'Terrace'), ('TL', 'Trail'), ('WY', 'Way'), ('W', 'West')], max_length=2, null=True)),
                ('last_synced', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Parcel',
            fields=[
                ('number', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('last_synced', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcels', to='lookups.Address')),
            ],
        ),
    ]
