#!/bin/sh
set -e

# Dev requirements, add --allow-unsafe in newer version of pip-tools
pip-compile requirements.in requirements-dev.in --output-file requirements-dev.txt $@
# Production requirements
pip-compile requirements.in requirements-prod.in --output-file requirements.txt $@
